version: '3.9'
services:
  mysql-invoices:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: invoices
      MYSQL_USER: invoices
      MYSQL_PASSWORD: invoices
      MYSQL_ROOT_PASSWORD: root
    ports: [ "3307:3306" ]
    command: [ "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
  mysql-mappings:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mappings
      MYSQL_USER: mappings
      MYSQL_PASSWORD: mappings
      MYSQL_ROOT_PASSWORD: root
    ports: [ "3308:3306" ]
    command: [ "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
