server:
  port: 8080
  servlet:
    context-path: /invoice-mapping

spring:
  application:
    name: invoicextract-mapping-service
  datasource:
    jdbc-url: ${MAPPINGS_DB_URL:jdbc:mysql://mysql-mappings:3306/mappings}
    username: ${MAPPINGS_DB_USER:root}
    password: ${MAPPINGS_DB_PASS:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

# Invoices DB (para uso futuro con JDBC/JPA read-only)
invoicesdb:
  url: ${INVOICES_DB_URL:jdbc:mysql://mysql:3306/invoices}
  username: ${INVOICES_DB_USER:root}
  password: ${INVOICES_DB_PASS:root}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
